Dataset cleaning

In [1]:
import pandas as pd

In [2]:
Telecom = pd.read_csv('telecom_churn.csv')
Telecom

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [3]:
Telecom.shape

(3333, 21)

In [4]:
Telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB

In [5]:
Telecom.isnull().sum()

state                     0
account length            0
area code                 0
phone number              0
international plan        0
voice mail plan           0
number vmail messages     0
total day minutes         0
total day calls           0
total day charge          0
total eve minutes         0
total eve calls           0
total eve charge          0
total night minutes       0
total night calls         0
total night charge        0
total intl minutes        0
total intl calls          0
total intl charge         0
customer service calls    0
churn                     0
dtype: int64

In [6]:
Telecom.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3328    False
3329    False
3330    False
3331    False
3332    False
Length: 3333, dtype: bool

In [10]:
Telecom['Total Minutes'] = Telecom['total day minutes'] + Telecom['total eve minutes'] + Telecom['total night minutes'] + Telecom['total intl minutes']

In [11]:
Telecom['Total Calls'] = Telecom['total day calls'] + Telecom['total eve calls'] + Telecom['total night calls'] + Telecom['total intl calls']

In [13]:
Telecom['Total Charge'] = Telecom['total day charge'] + Telecom['total eve charge'] + Telecom['total night charge'] + Telecom['total intl charge']

In [18]:
churncount = Telecom.groupby('churn')['phone number'].count()
churncount

churn
False    2850
True      483
Name: phone number, dtype: int64

In [57]:
def churn(value):
    if value == True:
        return 1
    else:
        return 0

In [ ]:
Telecom['Churn Count'] = Telecom['churn'].apply(churn)

0       0
1       0
2       0
3       0
4       0
       ..
3328    0
3329    0
3330    0
3331    0
3332    0
Name: Churn Count, Length: 3333, dtype: int64

In [30]:
def customer(value):
    if value <= 1:
        return "Low"
    elif value >=2 and value <=3:
        return 'Medium'
    else:
        return 'High'

In [31]:
Telecom['Costomer Service Frequency'] = Telecom['customer service calls'].apply(customer)

In [43]:
def minutes(value):
    if value <= 500:
        return "Low User"
    elif value > 500 and value <=600:
        return 'Medium User'
    else:
        return 'High User'

In [44]:
Telecom['User Value'] = Telecom['Total Minutes'].apply(minutes)

In [60]:
Telecom

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total intl calls,total intl charge,customer service calls,churn,Total Minutes,Total Calls,Total Charge,Churn Count,Costomer Service Frequency,User Value
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,3,2.70,1,False,717.2,303,75.56,0,Low,High User
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,3,3.70,1,False,625.2,332,59.24,0,Low,High User
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,5,3.29,0,False,539.4,333,62.29,0,Low,Medium User
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,7,1.78,2,False,564.8,255,66.80,0,Medium,Medium User
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,3,2.73,3,False,512.0,359,52.09,0,Medium,Medium User
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,6,2.67,2,False,660.7,292,60.10,0,Medium,High User
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,4,2.59,3,False,585.4,239,63.53,0,Medium,Medium User
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,6,3.81,2,False,675.6,264,67.74,0,Medium,High User
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,10,1.35,2,False,517.6,336,57.53,0,Medium,Medium User
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,4,3.70,0,False,755.4,276,77.01,0,Low,High User